name: Sync with upstream
on: 
 # schedule:
   # - cron: '30 2 * * *'
  workflow_dispatch:

jobs:
  merge-upstream:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Sync Repo
        run: gh repo sync ${{ github.repository }} -b main
        env:
          GH_TOKEN: ${{ secrets.PAT }}
